#!/bin/sh

set -e

if [ $# != 1 ]; then
    echo "usage: dnsmasq_conf_gen.sh domain.list"
    exit 1
fi

config=$1
line=1

output=./dnsmasq.conf
sysconf=/etc/dnsmasq.d/final.conf

error_exit()
{
    echo "$1" 1>&2
    exit 1
}

# 0. pre-check dependency
which ipset > /dev/null || error_exit "please install the ipset tool first"
which dnsmasq > /dev/null || error_exit "please install the dnsmasq app first"
test -f $config || error_exit "please re-check your input file arg, it doesn't exist"
touch .test || error_exit "please change to a place which you have the write permission or use 'sudo' to re-run this script"

# 1. clean up the output file
echo "# This is generated by dnsmasq_conf_gen on `date`" > $output

# 2. read the input file and generate a new dnsmasq.conf
cat $config | while read domain redirect; do
    if [ "$domain" == "" ] || [ "${domain:0:1}" == "#" ]; then
        continue
    fi

    echo "server=/$domain/127.0.0.1#1053" >> $output

    if [ "$redirect" != "off" ]; then
        echo "ipset=/$domain/final_iphash" >> $output
    fi

    echo "" >> $output

    line=`expr $line + "1"`
    echo "parse line $line successful"
done

# 3. diff with the sys dnsmasq.conf
touch $sysconf
diff -u $sysconf $output || echo "============================================================"

# 4. ask user whether should apply the changes, if yes, restart dnsmasq
read -p "Do you want to apply this changes and restart dnsmasq? (y/n)" action
if [ "$action" == "y" ]; then
    echo "backup sys dnsmasq.conf to ${sysconf}.bak"
    cp $sysconf ${sysconf}.bak

    echo "replace the $sysconf with $output"
    cp $output $sysconf

    echo "restarting dnsmasq..."
    /etc/init.d/dnsmasq restart
    echo "restart dnsmasq done, now enjoy!~"
else
    echo "Abort, please input 'y' if you want to apply these changes :)"
fi
